DROP TABLE IF EXISTS example;
CREATE TABLE IF NOT EXISTS example(id INT PRIMARY KEY, value INT);
INSERT INTO example VALUES (1, 10);
INSERT INTO example VALUES (2, 20);
INSERT INTO example VALUES (3, 30);